name: 🔄 به‌روزرسانی خودکار
on:
  push:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: 🛠️ کلون ریپو
        uses: actions/checkout@v3

      - name: 📦 نصب پیش‌نیازها
        run: |
          python -m pip install --upgrade pip
          pip install urllib3 ruamel.yaml

      - name: 🚀 اجرای اسکریپت
        run: python3 update_sublist.py

      - name: 💾 ذخیره تغییرات
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "🔄 به‌روزرسانی خودکار لیست‌ها و README"
          add: |
            Sublist/*
            README.md
            update.log
